config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  get 'pages/index'
  get 'pages/show'

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  enum status: %i(incomplete complete)

  belongs_to :user

  validates :title, presence: true
  validates :status, inclusion: { in: statuses.keys }

  scope :incomplete, -> { where(status: Todo.statuses[:incomplete]) }

  after_initialize :set_default, if: :new_record?

  scope :like_title, -> (title) { where('title LIKE ?', "%#{title}%") }
  scope :search, -> (search_form) {
    self.like_title(search_form.title).where(status: search_form.status)
  }

  private

  def set_default
    self.status ||= Todo.statuses[:incomplete]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @todo = Todo.where(user: current_user).incomplete.order("id DESC").first
  end

  def show
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @search_form = SearchTodosForm.new(search_todos_params)
    @todos = Todo.where(user: current_user).search(@search_form);
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(user: current_user, title: todo_params[:title], body: todo_params[:body])

    if @todo.save
      redirect_to todos_path, notice: 'ToDoを作成しました'
    else
      render :new
    end
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path, notice: 'ToDoを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path, notice: 'ToDoを削除しました'
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:title, :body, :status)
    end

    def search_todos_params
      params.fetch(:search_todos_form, {}).permit(:title, { status: [] }, :create_from, :create_to)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transition_link_helper.rb
module TransitionLinkHelper
  def render_new_link(url, klass: 'btn btn-default')
    link_to '新規作成', url, class: klass
  end

  def render_detail_link(url, klass: 'btn btn-default')
    link_to '詳細', url, class: klass
  end

  def render_edit_link(url, klass: 'btn btn-default')
    link_to '編集', url, class: klass
  end

  def render_update_link(url, klass: 'btn btn-default')
    link_to '更新', url, class: klass
  end

  def render_delete_link(url, klass: 'btn btn-danger')
    link_to '削除', url, method: :delete, data: { confirm: '本当に削除してもよろしいですか?' }, class: klass
  end

  def render_return_link(url, klass: 'btn btn-light')
    link_to '戻る', url, class: klass
  end

  def render_save_submit(form, klass: 'btn btn-lg btn-primary')
    text = form.object.persisted? ? '更新する' : '登録する'
    form.submit text, class: klass
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag :application %>
    <%= javascript_include_tag :application %>
  </head>

  <body>
    <header>
      <nav>
        <% if user_signed_in? %>
        <strong><%#= link_to current_user.username, pages_show_path %></strong>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'サインアップ', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
        <% end %>
      </nav>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>トップ</h1>

<% if @todo.present? %>
  最新の未達成ToDo
  <%= render 'parts/todo/show_detail', todo: @todo %>
<% else %>
  現在未完了のToDoはありません。
<% end %>

<div class="bottom-btn-field">
  <%= link_to "ToDoリスト", todos_path, class: 'btn btn-lg btn-light' %>
</div>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/parts/todo/_search_todos_form.html.erb
<div class='card' style="padding: 10px">
  <div class='card-body'>
    <%= form_for search_form, url: todos_path, method: :get, html: { class: 'form-horizontal' } do |f| %>
      <div class='form-group row'>
        <%= f.label :title, SearchTodosForm.human_attribute_name(:title), class: 'col-sm-2' %>
        <div class="col-sm-8">
          <%= f.send(:text_field, :title, class: 'form-control') %>
        </div>
      </div>
      <div class='form-group row'>
        <%= f.label :status, SearchTodosForm.human_attribute_name(:status), class: 'col-sm-2' %>
        <div class="col-sm-8">
          <%= f.collection_check_boxes(:status, Todo.statuses, :first, :last, include_hidden: false) do |c| %>
            <%= c.label { c.check_box(checked: search_form.status.try(:include?, c.value)) + I18n.t(c.value, scope: [:enum, :status]) } %>
          <% end %>
        </div>
      </div>
      <div>
        <%= button_tag('検索', value: 'html', name: 'format', class: 'btn btn-primary') %>
      </div>
    <% end %>
  </div>
</div>

app/views/parts/todo/_show_detail.html.erb
<table class="table table-hover">
  <tr>
    <th><%= Todo.human_attribute_name(:status) %></th>
    <td><%= I18n.t(todo.status, scope: [:enum, :status]) %></td>
  </tr>
  <tr>
    <th><%= Todo.human_attribute_name(:title) %></th>
    <td><%= todo.title %></td>
  </tr>
  <tr>
    <th><%= Todo.human_attribute_name(:body) %></th>
    <td><%= todo.body %></td>
  </tr>
</table>

app/views/parts/todo/_todo.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= Todo.human_attribute_name(:status) %></th>
      <th><%= Todo.human_attribute_name(:title) %></th>
      <th>操作</th>
    </tr>
  </thead>
  
  <tbody>
    <% todos.each do |t| %>
      <tr>
        <td>
          <%= I18n.t(t.status, scope: [:enum, :status]) %>
        </td>
        <td><%= t.title %></td>
        <td>
          <%= render_detail_link t %>
          <%= render_edit_link edit_todo_path(t) %>
          <%= render_delete_link t %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |f| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <table class='table-hover col-sm-12'>
      <% if todo.persisted? %>
      <tr>
        <th><%= Todo.human_attribute_name(:status) %></th>
        <td><%= f.select :status, Todo.statuses.map { |k, v| [I18n.t(k, scope: [:enum, :status]), k] }, class: 'form-control' %></td>
      </tr>
      <% end %>
      <tr>
        <th><%= Todo.human_attribute_name(:title) %></th>
        <td><%= f.text_field :title, class: 'form-control' %></td>
      </tr>
      <tr>
        <th><%= Todo.human_attribute_name(:body) %></th>
        <td><%= f.text_area :body, class: 'form-control' %></td>
      </tr>
    </table>
  </div>

  <div class="actions">
    <%= render_save_submit f %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1><%= Todo.model_name.human %>編集</h1>
<%= render 'form', todo: @todo %>
<%= render_return_link todos_path %>

app/views/todos/index.html.erb
<h1><%= Todo.model_name.human %>一覧</h1>

<%= render 'parts/todo/search_todos_form', search_form: @search_form %>
<%= render_new_link new_todo_path %>
<%= render 'parts/todo/todo', todos: @todos if @todos.present? %>

<div class="bottom-btn-field">
  <%= link_to 'トップへ', pages_index_path, class: 'btn btn-lg btn-light' %>
</div>

app/views/todos/new.html.erb
<h1><%= Todo.model_name.human %>新規作成</h1>

<%= render 'form', todo: @todo %>

<div class="bottom-btn-field">
  <%= render_return_link todos_path %>
</div>

app/views/todos/show.html.erb
<h1><%= Todo.model_name.human %>詳細</h1>
<%= render 'parts/todo/show_detail', todo: @todo %>

<div class="bottom-btn-field">
  <%= render_edit_link edit_todo_path(@todo) %>
  <%= render_return_link todos_path %>
</div>